### ISSUE TITLE
Loads and I get splash screen then nothing else just running process

### ISSUE THREAD

**Issue by chronic8000** [sebdelsol/sfvip-all#32]
From Windows Event Viewer:

Faulting application name: SFVipPlayer.exe, version: 1.2.7.86, time stamp: 0x96fd54ec
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4249, time stamp: 0x0cf64c6a
Exception code: 0xe0434352
Fault offset: 0x000000000005fe4c
Faulting process id: 0x0x63FC
Faulting application start time: 0x0x1DB23D92AD6F598
Faulting application path: C:\Users\chron\Downloads\svip\SFVipPlayer.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 1c41b4c8-da8b-433e-badb-1181ee2da68f
Faulting package full name: 
Faulting package-relative application ID: 

Application: SFVipPlayer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.Drawing.Icon.ExtractAssociatedIcon(System.String, Int32)
   at libthemes.Controls.MetroWindow.TrayIconHandler()
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Windows.Window.OnSourceInitialized(System.EventArgs)
   at System.Windows.Window.CreateSourceWindow(Boolean)
   at System.Windows.Window.ShowHelper(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at SFVipPlayer.App.Main()

**Comment by yagotour** [comment]
+1

**Comment by vgcouso** [comment]
The same thing happens to me
